"""drop likes from posts

Revision ID: 5ba4c3ceef35
Revises: 1a90f850eaec
Create Date: 2026-09-18 20:37:41.462634

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5ba4c3ceef35"
down_revision: Union[str, Sequence[str], None] = "1a90f850eaec"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("posts", "likes")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "posts", sa.Column("likes", sa.INTEGER(), server_default=sa.text("0"), autoincrement=False, nullable=False)
    )
    # ### end Alembic commands ###
